# Run all the examples

.PHONY: all run-length-encoding sliding-window

all: tryfirst run-length-encoding sliding-window

tryfirst:
	cd TryFirst && $(MAKE)

run-length-encoding:
	cd run-length-encoding && $(MAKE)

sliding-window:
	cd sliding-window && $(MAKE)

